### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [dangne/devc-datascience#1]
Hello Dang Minh Nguyen,
Assignment 1:
- Problem 5: Task Given an integer, perform the following conditional actions: ... The result will be wrong when n = 21. 
 + Actually result: Weird.
+  Expected result: Not Weird.

**Comment by dangne** [comment]
Sorry but I have to disagree.

n = 21 is an **odd number**.
The only condition that is satisfied is the first one
Therefore, the correct result must be **"Weird"**
